%Each new term in the Fibonacci sequence is generated by adding the previous two
% terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not exceed
% four million, find the sum of the even-valued terms.

Prvi=1;
Drug=2;
Suma=2;

Uvjet=1
Limit=4*1000*1000;

while (Uvjet==1)

  Temp=Drug;
  Drug=Drug+Prvi;
  Prvi=Temp;

  if (Drug>Limit);     break;          end
  if (mod(Drug,2)==0); Suma=Suma+Drug; end

  disp(Drug);
end

disp('---------')
disp(Suma);
disp('---------')
